# Local DB
spring:
  profiles:
    include: aws
  datasource:
    url: jdbc:mysql://localhost:3306/hunstagram
    username: hunseong
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

# JPA
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 100

# Logging level
logging:
  level:
    com:
      example:
        hunstagram: debug
